#!/bin/sh
# X init script
# Sources xprofile, loads Xresources, starts WM

# Load X resources
xrdb -I"$HOME/dotfiles" -merge "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources"

# Load X profile (autostart apps)
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ] && . "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"

# Keyring
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK

# DBus/systemd integration
systemctl --user import-environment DISPLAY XAUTHORITY
dbus-update-activation-environment --systemd DISPLAY XAUTHORITY

# Start window manager
exec dwm
