# roles/starship/files/starship.toml
format = "$username@$hostname:$directory$git_branch$character"

[username]
show_always = true
format = "$user"

[hostname]
ssh_only = false
format = "$hostname"

[directory]
truncation_length = 0
truncate_to_repo = false
format = "$path"

[git_branch]
format = " \\[$branch\\]"

[character]
success_symbol = " \\$"
error_symbol = " \\$"

# Disable all other modules
[aws]
disabled = true
[gcloud]
disabled = true
[nodejs]
disabled = true
[python]
disabled = true
[rust]
disabled = true
[golang]
disabled = true
[package]
disabled = true
[docker_context]
disabled = true
[cmd_duration]
disabled = true
